// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMS.Db;

#nullable disable

namespace QMS.Migrations
{
    [DbContext(typeof(QmsDbContext))]
    [Migration("20250817181730_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("QMS.DTO.FrontDeskTerminal", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DeviceId");

                    b.ToTable("FrontDeskTerminals");
                });

            modelBuilder.Entity("QMS.DTO.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FrontDeskTerminalDeviceId")
                        .HasColumnType("varchar(191)");

                    b.Property<string>("FrontDeskTerminalId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FrontDeskTerminalDeviceId");

                    b.HasIndex("FrontDeskTerminalId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("QMS.DTO.Ticket", b =>
                {
                    b.HasOne("QMS.DTO.FrontDeskTerminal", null)
                        .WithMany("Tickets")
                        .HasForeignKey("FrontDeskTerminalDeviceId");

                    b.HasOne("QMS.DTO.FrontDeskTerminal", "FrontDeskTerminal")
                        .WithMany()
                        .HasForeignKey("FrontDeskTerminalId");

                    b.Navigation("FrontDeskTerminal");
                });

            modelBuilder.Entity("QMS.DTO.FrontDeskTerminal", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
