// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QMS.Db;

#nullable disable

namespace QMS.Migrations
{
    [DbContext(typeof(QmsDbContext))]
    partial class QmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("QMS.DAL.FrontDeskTerminal", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.ToTable("FrontDeskTerminals");
                });

            modelBuilder.Entity("QMS.DAL.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontDeskTerminalDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontDeskTerminalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrontDeskTerminalDeviceId");

                    b.HasIndex("FrontDeskTerminalId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("QMS.DAL.Ticket", b =>
                {
                    b.HasOne("QMS.DAL.FrontDeskTerminal", null)
                        .WithMany("Tickets")
                        .HasForeignKey("FrontDeskTerminalDeviceId");

                    b.HasOne("QMS.DAL.FrontDeskTerminal", "FrontDeskTerminal")
                        .WithMany()
                        .HasForeignKey("FrontDeskTerminalId");

                    b.Navigation("FrontDeskTerminal");
                });

            modelBuilder.Entity("QMS.DAL.FrontDeskTerminal", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
