apiVersion: v1
kind: Service
metadata:
  name: qms-service
  namespace: qms
spec:
  type: ClusterIP
  selector:
    app: qms-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
